### ISSUE TITLE
Forms are being duplicated (one created on changing to Live, one created on Save)

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#106]
You can see the dupe forms here: https://web01_stg.coralproject.net/forms

**Comment by impronunciable** [comment]
@kgardnr I *think* I spotted the issue here https://github.com/coralproject/cay/pull/666 can you try to reproduce it after that's merged?

thanks!

**Comment by kgardnr** [comment]
@impronunciable yes will do!
