### ISSUE TITLE
CSV bugs to fix

### ISSUE THREAD

**Issue by jde** [coralproject/ask#120]
https://pillar_stg.coralproject.net/v1/form/57955fe7d05a1e00059dbff3/submission/csv

- [x] Remove "text:" or "value:" from the beginning of each string
- [x] Escape: new lines , (\,) inside of strings, and consider surrounding strings with "" and escape quotes (\") whichever is more idiomatic for csv

https://pillar_stg.coralproject.net/v1/form/57955fe7d05a1e00059dbff3/submission?skip=0&limit=10&orderby=dsc&filterby=&search=
- [x] The csv_url reported to the fe is empty

- [x] Capture answers if question title is ""

COLUMNS
- [x] Submission ID as first column
- [x] Timestamp for second column (Created/submitted Date)
- [x] "Flagged? column (after answers) - Show "Yes" if flagged, blank if not flagged
- [x] "Bookmarked?" column (after answers) - Show "Yes" if bookmarked, blank if not bookmarked

MULTIPLE CHOICE
- [x] Need to handle multiple choice like this: https://docs.google.com/spreadsheets/d/1YRE4BB4_ogCUMELlHySpmYdQG6nuEYLjZzzhqD7o5rw/edit#gid=0
Currently outputting like this:
<img width="855" alt="mult_choice_csv" src="https://cloud.githubusercontent.com/assets/1077300/18530191/579a9112-7a9e-11e6-8802-39f308a8f4f1.png">
Form to replicate if needed: https://web01_stg.coralproject.net/forms/57d9bbdb0cefe52b9d1123ec/submissions

**Comment by gabelula** [comment]
About multiple choice (multiple options) I'm not sure that adding a column per choice is the best way to do it. I like how Google Forms is exporting it as one column with comma-separated values. For example: "Choice1, Choice5"

**Comment by gabelula** [comment]
For the flags it is kind of confusing how we are storing them. When it is flagged we are storing a string "true" in the Flags slice. When it is bookmarked we are storing a string "bookmarked" in the Flags slice. Not sure how to divide this in different columns when is not clear how it is store. Right now I'm exporting a column "Flags" with all the values in the flags slice.
