### ISSUE TITLE
Styles to make embedded form work on mobile for Coral blog

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#122]
[Standalone Form_stacked questions mobile.pdf](https://github.com/coralproject/ask/files/483147/Standalone.Form_stacked.questions.mobile.pdf)

**Comment by kgardnr** [comment]
Looks like main difference is making the multiple choice boxes full-width

<img width="548" alt="fullscreen_9_20_16__12_53_pm" src="https://cloud.githubusercontent.com/assets/1077300/18680352/526bc89a-7f31-11e6-949b-daaece540aa4.png">

**Comment by okbel** [comment]
![out](https://cloud.githubusercontent.com/assets/1401559/18683056/0d156d0a-7f45-11e6-8050-7af5774af86e.gif)

@kgardnr does that look good?

**Comment by okbel** [comment]
https://github.com/coralproject/elkhorn/pull/109
