### ISSUE TITLE
Bug: Cannot save on staging due to config issue

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#126]
<img width="1280" alt="fullscreen_9_22_16__2_34_pm" src="https://cloud.githubusercontent.com/assets/1077300/18763454/775eaee6-80db-11e6-8e79-b577e3a4d60b.png">

**Comment by okbel** [comment]
<img width="1280" alt="screen shot 2016-09-23 at 10 35 56 am" src="https://cloud.githubusercontent.com/assets/1401559/18787518/8ed5b300-8179-11e6-8e72-68038a1984fe.png">

I wasn't able to reproduce the issue. @kgardnr
