### ISSUE TITLE
Implement design standards for Gallery Manager page (gallery create/edit)

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#129]
[coral_mdl_styles.pdf](https://github.com/coralproject/ask/files/490095/coral_mdl_styles.pdf)

**Comment by kgardnr** [comment]
@egrdina to add Card design for this.

**Comment by egrdina** [comment]
Updated style guide here: 
[Coral MDL Styles.pdf](https://github.com/coralproject/ask/files/498811/Coral.MDL.Styles.pdf)
