### ISSUE TITLE
Add Ask version number

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#131]
AC:
- Issue number into the bottom left beneath Collapse Menu
- Taken from VERSION file that David created
- Design below

![screen shot 2016-09-28 at 5 10 50 pm](https://cloud.githubusercontent.com/assets/1077300/18970667/22517c6e-8660-11e6-86ec-6ac0f0ad3857.png)

**Comment by pablocubico** [comment]
Heads up! The version file wouldn't be accessible from the browser on a production environment, since it's outside the public scope. I guess the version file should be added to the dist folder when running `npm run build`, or maybe just move it to the `public` folder.
