### ISSUE TITLE
Accessibility for Reader Facing Forms 

### ISSUE THREAD

**Issue by IAmSamHankins** [coralproject/ask#135]
Reader facing forms do not use <label> for their respective questions/inputs as required by WCAG 2.0 AA (therefore making our forms inaccessible).

https://www.w3.org/WAI/tutorials/forms/

Tested on Coral Project contact page

![screenshot 2016-10-12 16 55 02](https://cloud.githubusercontent.com/assets/12632662/19327433/086ae320-909d-11e6-882b-2aa5c85aa847.png)

**Comment by kgardnr** [comment]
Closed and moved to PT: https://www.pivotaltracker.com/story/show/132279949
