### ISSUE TITLE
Heroku Quickstart Fails during build

### ISSUE THREAD

**Issue by jcockhren** [coralproject/ask#138]
Hey all!
I attempted to install Ask using the "Deploy to Heroku" quickstart button. The app fails during the build stage. Any thoughts or advice?
![ask_deploy_to_heroku](https://cloud.githubusercontent.com/assets/316840/19564360/efd834f4-96a8-11e6-968d-9e0efd23ad65.png)

Alternatively, I attempted to follow the [Advanced Setup for Linux](http://coralprojectdocs.herokuapp.com/user/ask/#advanced-setup-linux) however, it seems that the docker components aren't present in the repo anymore as of #137 

@jtnelson Want to pair on this?

**Comment by jtnelson** [comment]
@jcockhren Thanks for flagging this. We're pushing out some new install artifacts later today and updating the Heroku installer. I'll ping you when they're ready and we can test to make sure its all working for you!

**Comment by kgardnr** [comment]
Hi @jcockhren, we have currently tabled the Heroku one-click install. 

You can follow the current Ask install process here: https://docs.coralproject.net/products/ask/

Let us know if you have questions, you can always reach out to Jeff directly: jeff@mozillafoundation.org

Thanks! :)
Kim & The Coral Team
