### ISSUE TITLE
Feature Request: SSO integration

### ISSUE THREAD

**Issue by dj** [coralproject/ask#143]
Hi, I'm a dev at www.technologyreview.com and we're trying to integrate Ask with our site.

Authentication is our only blocker right now to using Ask. I was wondering if SSO integration is being considered? This would be the ideal UX for our editors, writers and producers.

**Comment by jtnelson** [comment]
@dj thanks for filing this. We're looking into whether this is currently possible, and if not, what would be required to enable it. Will get back to you shortly!

**Comment by dj** [comment]
Thanks @jtnelson. If SSO isn't coming soon, I'm sure we could manage with other authentication options (gmail, facebook, etc) so I would be interested in knowing what the status is of authentication in general.

**Comment by dj** [comment]
@jtnelson how are current users of Ask authenticating their installation?

**Comment by jtnelson** [comment]
@dj current Ask users are using the built-in authentication that leverages Coral's built-in auth server. I'm going to shoot you an email to setup a call so we can discuss your particular SSO needs. That can serve as a guide as we implement SSO for Ask, in general

**Comment by dj** [comment]
I think the Ask documentation should be updated to point the user in that direction. It's not really mentioned in the docs or on anything else I've read on the coral project site. I see now by exploring your github that this is probably what you're talking about https://github.com/coralproject/coral-auth
https://docs.coralproject.net/products/ask/

**Comment by jtnelson** [comment]
@dj I'm going to close this assuming that and open a new issue to update the documentation.
