### ISSUE TITLE
No coral-ask-ami on Marketplace

### ISSUE THREAD

**Issue by mattlinares** [coralproject/ask#144]
I'm following instructions here to get the Machine Image:

https://docs.coralproject.net/products/ask/  1A

so [search `coral-ask-ami` here](https://aws.amazon.com/marketplace/search/results?x=0&y=0&searchTerms=coral-ask-ami&page=1&ref_=nav_search_box) and get the message:

"No search results for "coral-ask-ami""

Any ideas? Thanks!

**Comment by jtnelson** [comment]
Wanted to close the loop here: The `coral-ask-ami` is on the `us-east-1` region. We'll add it to additional regions in the coming weeks.
