### ISSUE TITLE
Submission Gallery design review

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#15]
- [x] Modal

<img width="713" alt="screen shot 2016-07-25 at 10 38 12 am" src="https://cloud.githubusercontent.com/assets/1077300/17105202/dfc2466e-524b-11e6-864b-a7872ecf7266.png">

- [x] Standalone Gallery link should open in a new tab

- [x] Gallery page

**Comment by egrdina** [comment]
Yes! Great catch @davidgljay
