### ISSUE TITLE
Docker file for this repo (Go executable)

### ISSUE THREAD

**Issue by davisshaver** [coralproject/ask#156]
As mentioned in https://github.com/coralproject/ask/pull/155, I was looking at putting Ask and Talk on the same server today.

As I was reviewing things I thought that it might be nice for us to have a Docker container that wrapped the Go executable from Ask Install. This is not my forte but quick Google search suggests it should be possible. https://medium.com/developers-writing/docker-powered-development-environment-for-your-go-app-6185d043ea35

Just looking for feedback at this point. cc @wyattjoh

**Comment by wyattjoh** [comment]
Unfortunately, Ask requires a set of microservices to run correctly. If we were to better support a Docker method, id suggest using a k8s based strategy.

**Comment by davisshaver** [comment]
@wyattjoh Hm, ok. I've not used k8s myself yet. I guess that would be **instead** of Docker rather than **in conjunction** with Docker?

I'd be open to changing ticket to be more generic ("Easier setup for Ask tool") if you agree in principle, my take from the outside is that Ask right now is a bit more complex than Talk to get going.

**Comment by wyattjoh** [comment]
The issue with Ask currently is that it requires this multi-application micro services model to run, which by nature, is difficult to setup. My hopes are, with some time, we can create .deb files for installation that would truly automate the process, but that's a ways off for the time being. The best recommendation for installation is to use the https://github.com/coralproject/ask-install binary to assist the installation.

**Comment by cvle** [comment]
@wyattjoh I'm not very familiar with Ask, but wouldn't `docker-compose` solve exactly that use case?

**Comment by cvle** [comment]
https://docs.docker.com/compose/

**Comment by davisshaver** [comment]
@wyattjoh @cvle I'm down to tinker with Docker compose setup if someone wants to point me in the right direction. @wyattjoh, you mentioned the binary, is there anyway we can shove that into a container somehow? OR maybe you could link to where the microservice setup is defined? thanks for all the work! 🍺

**Comment by wyattjoh** [comment]
The ask installer https://github.com/coralproject/ask-install simply generates a docker-compose.yml file, so wrapping that in a docker container would be kind of redundant ;) Check out this template https://github.com/coralproject/ask-install/blob/master/templates/docker-compose.yml for a layout of the services involved.
