### ISSUE TITLE
Make published forms and galleries directly targetable

### ISSUE THREAD

**Issue by jde** [coralproject/ask#20]
We are publishing static galleries and forms.  The links that we use to target them, however, proxy through elkhorn.  

- [ ] Update our publishing model so that published assets are standalone.
- [ ] Update all links to target the files directly

**Comment by pablocubico** [comment]
As of now we are building a single JS bundle per Form as: **[someid].js**

This file is used in the embed code option:
```
<div id="ask-form"></div><script src="http://localhost:4444/widgets/57a20634c29ca00006dfa8f2.js"></script>
```

To serve a standalone file we could:
a) create an HTML file with the iframe code and the JS bundle
b) create an HTML file with the iframe code referencing the JS bundle

That said, you still need some web server to host these files and make them accesible.

On the funny side of things, looks like Amazon forces download of HTML files:
https://s3.amazonaws.com/nyt-stage/57a20634c29ca00006dfa8f2.html

**Comment by pablocubico** [comment]
Pinging @impronunciable too for opinions.

**Comment by impronunciable** [comment]
@pablocubico 

1 - I'll go for a) that will make the form render FAST (also we can add a SW and make it work offline (?))

2 - The download force can be mitigated setting the content type as text/html

**Comment by pablocubico** [comment]
So, this is mostly working except that we need to store at least the base URL somewhere, as we are doing some hardcodish duct-taping to show the URLs.

- Since Cay does not know if S3 is configured in Elkhorn, I'm providing full URLs to Cay.
- Most Cay URLs are based on `elkhornHost`, using Elkhorn as proxy.
- I think we should persist at least the base URL, so we can construct a proper URL

Related PRs:
https://github.com/coralproject/elkhorn/pull/79
https://github.com/coralproject/cay/pull/587

**Comment by jde** [comment]
Couldn't we bundle the js and html together into a single file? Seems creating an html file that simply loads a js file will add complexity and cost a request.

**Comment by pablocubico** [comment]
So, should we create an issue to make Pillar store the address?

**Comment by kgardnr** [comment]
I'm removing the "blocked" tag since @pablocubico is going to do the pillar work.

cc @jde

**Comment by impronunciable** [comment]
@pablocubico is this for review now?

**Comment by pablocubico** [comment]
not yet! working on it

**Comment by jde** [comment]
Concerning where to save the location(s) of published file(s), the `settings` parameter is of type _interface{}_ meaning that it will capture and return any data structures that you throw at it. You can add the published locations with no updates to Pillar like so:

```
  form.settings.publishedUrl
```

**Comment by pablocubico** [comment]
This is now ready for review, we are storing the `baseUrl` for a **form** in: 
```
form.settings.baseUrl
```
and the one for a **gallery** in
```
gallery.config.baseUrl
```
Which is also of `interface{}` type on PIllar.

### What to test
Create a form and check all the embed codes, they should reflect your `Elkhorn` config (S3 or filesystem). Publish a gallery and do the same check.
