### ISSUE TITLE
Validation for phones seems not to be working

### ISSUE THREAD

**Issue by malon** [coralproject/ask#39]
Just a bunch of letters were accepted as a phone.

**Comment by losowsky** [comment]
Very well spotted @malon - phone numbers are tricky. We can validate for some countries, or validate for numbers and symbols only (so it can accept ( ) and - and +) - but what about people who need to leave an "extension"?

So why, I telepathically hear you ask, have it as a separate field at all, to create what is really just a short answer field that is labelled as PII? This is more for journalist-end users, to a) avoid them picking the 'numbers' field without thinking about the above needs, b) to remind them that they might want to collect phone numbers, and c) to label those automatically as PII to avoid potential user data issues later. 

Does that make sense? And do you think we're going about it in the right way?

**Comment by malon** [comment]
Hi Andrew!
Sorry for the the delay. I'm on holidays just moving around the country :).

Reasons a) and b) make a lot of sense, regarding c) I understand you use
this field as a primary key then?, but you could have duplicates (company's
phone without extension?) so I guess you only consider the phone field if
it is unique.

Still, some kind of validation could be done, looking for a minimum amount
of numbers in the field for example, increasing the possibilities of having
a real valid number as the answer. Also, a place holder showing a typical
phone format, including an extension and a country code, could be useful to
remember users to add it if necessary.

I'm just thinking out loud here, as you asked about my thoughts on this.

Thank you for your explanations!
Cheers

Marta

**Comment by losowsky** [comment]
Thanks Malon! A placeholder for typical / requested format is a great idea. Thanks so much for filing the issue, and for responding. Have a great vacation :)
