### ISSUE TITLE
Hand icon on currently selected nav item makes no sense

### ISSUE THREAD

**Issue by gidsg** [coralproject/ask#40]
# Steps to reproduce
Go to: http://192.168.99.100/forms/create
Hover over 'Build forms'

# Actual Results
Cursor changes to hand but click performs no action

# Expected Results
Do not show hand cursor on currently selected item

**Comment by kgardnr** [comment]
Thank you for this awesome feedback! We are doing an overall design polish for the Beta 2 product, and will definitely address this issue.

Closing for now and will address in another issue.

Thanks again!
Kim
