### ISSUE TITLE
Option to automatically publish approved submissions to gallery

### ISSUE THREAD

**Issue by gidsg** [coralproject/ask#42]
# RFE
Currently, each time I approve a submission, in order to have it appear in a gallery, I need to go to the Gallery tab and re-publish. It would be good to have the option to automatically, approve and re-publish gallery in one click. To avoid the additional clicks each time I want to update the gallery.

**Comment by kgardnr** [comment]
Hi @gidsg, thank you for the feedback! This feature is not in our roadmap at the moment, but I will note this in our Trello board for future features. Thank you again!
Kim & The Coral Project Team
