### ISSUE TITLE
Admin can manage tags for submissions

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#44]
<img width="652" alt="screen_shot_2016-07-12_at_4 50 03_pm" src="https://cloud.githubusercontent.com/assets/1077300/17338826/a6b17b7e-58ae-11e6-8ec8-9e6ca71eeae0.png">

<img width="657" alt="screen_shot_2016-07-12_at_4 49 59_pm" src="https://cloud.githubusercontent.com/assets/1077300/17338827/a82c22b0-58ae-11e6-9194-ea4fc14da510.png">

<img width="654" alt="screen_shot_2016-07-12_at_4 49 53_pm" src="https://cloud.githubusercontent.com/assets/1077300/17338830/ab58dee2-58ae-11e6-9909-923305d285c1.png">

<img width="666" alt="screen_shot_2016-07-12_at_4 48 42_pm" src="https://cloud.githubusercontent.com/assets/1077300/17338834/b0695150-58ae-11e6-9824-8097d3f9f5ca.png">

**Comment by impronunciable** [comment]
@jde are this tags already available to use?

**Comment by jde** [comment]
Forms have a "Flags" field that can store any kind of text. The initial thought was that these can be used for Tags as well.  This makes querying for any sort of text based tag/flag/etc... the same as far as the backend is concerned.

**Comment by jde** [comment]
Also, I believe that these are "ad hoc" tags. The user types them in and they are there, so there's no concept of choosing from a preset bunch of tags. @egrdina, @losowsky, please correct me if I'm wrong.

**Comment by impronunciable** [comment]
@jde so should I use the flags array and filter flagged and bookmarked? (that would make things much easier for me)

**Comment by jde** [comment]
Yes. That would be ideal.

**Comment by impronunciable** [comment]
💥

**Comment by impronunciable** [comment]
PR is here https://github.com/coralproject/cay/pull/609
