### ISSUE TITLE
Reader can easily copy embed links and scripts for the Gallery

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#46]
- Add "Copy" buttons to Form embeds
- Add "Copy" buttons to Gallery embeds

**Comment by egrdina** [comment]
This modal launches after a user clicks "Get embed codes" 
![screen shot 2016-08-02 at 11 29 55 am](https://cloud.githubusercontent.com/assets/7856099/17334502/79461a6e-58a4-11e6-9020-484e5c8d8a73.png)

**Comment by egrdina** [comment]
![screen shot 2016-08-03 at 11 21 50 am](https://cloud.githubusercontent.com/assets/7856099/17371058/81ba6e98-596c-11e6-874f-82175aa8b2e7.png)
