### ISSUE TITLE
Admin can duplicate a form

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#47]
- Designs below
- Copied form title should be "My Awesome Form (Copy)"
- On Copy, open Create Form modal (on Create/Edit page)
- Duplicates form but not submissions or galleries

**Comment by egrdina** [comment]
The button to the left of the trash icon duplicates a form. 
![screen shot 2016-08-02 at 11 33 41 am](https://cloud.githubusercontent.com/assets/7856099/17334648/030812d4-58a5-11e6-9703-99ba9daa6f59.png)

**Comment by davidgljay** [comment]
I take it new forms should be closed by default?

**Comment by davidgljay** [comment]
This is complete, but I have a design question before submission:

The copy function needs to roundtrip to the server before completion, which could take up to a few seconds. It seems like we should replace the copy icon with a progress indicator while this is happening. Do we want this to be the material design progress indicator or the one currently used in the "Save" button on the form edit screen?

**Comment by egrdina** [comment]
@davidgljay is there a link where @IAmSamHankins and I could see this action happening? I want to make sure we're understanding the suggestion correctly.

**Comment by davidgljay** [comment]
@egrdina The copy button goes to a special version of the /form/create screen that starts with the language from the form being copied.

**Comment by pablocubico** [comment]
Is there a PR for this?

**Comment by davidgljay** [comment]
yes, sorry. It's been merged. https://github.com/coralproject/cay/pull/613
