### ISSUE TITLE
Admin can export submission data as a CSV

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#48]
- Design below
- Example CSV output: https://docs.google.com/spreadsheets/d/1YRE4BB4_ogCUMELlHySpmYdQG6nuEYLjZzzhqD7o5rw/edit?usp=sharing
- CSV exports ALL submissions
- Question column headers are the Questions themselves (e.g. What's your favorite color?)

![screen_shot_2016-07-25_at_5 19 31_pm](https://cloud.githubusercontent.com/assets/1077300/17527388/c9deec44-5e30-11e6-9ce0-ace0202a1cd9.png)

**Comment by wyattjoh** [comment]
Would it be expected that `ask` would provide the csv file or would the frontend load in the csv data from a json payload and then download it to the client there?

**Comment by jde** [comment]
My thought was that the api would generate the csv content and deliver it as with a csv content type. This would allow the user the most flexibility in handling it.

**Comment by ardan-bkennedy** [comment]
@jde @gabelula @kgardnr This is a bad idea. It will create a very inconsistent API. We must always return JSON and be very consistent how we do that for each API set. If the consuming application needs to transform the data they need to do it. I can't tell you how many BAD API's I have worked with that do this. It is a nightmare for the consuming applications. Please can we not do this from our API?

**Comment by ardan-bkennedy** [comment]
If this is an absolute must, which I hope it isn't, then it must be embedded into the standard JSON response document in some consistent fashion.

**Comment by wyattjoh** [comment]
Would recommend something like this: https://stackoverflow.com/questions/14964035/how-to-export-javascript-array-info-to-csv-on-client-side

**Comment by pablocubico** [comment]
Hm, that's clever, I wonder if there are any downsides.

**Comment by ardan-bkennedy** [comment]
Nothing trumps Integrity. Not having a consistent request/response that is all in JSON breaks the integrity promise. We must be using status code for error handling and the response must be consistent for errors and when things go right.

This will also lend to readability and simplicity as well since there are no surprises.

JSON is (JavaScript Object Notation)

**Comment by impronunciable** [comment]
So if there are 5000 answers the frontend will need to download a n MB file and then parse it into a csv and make the user download it again? I heard this discussion on server integrity more than once, but that's the Content-Type header for, right? In fact in an ideal world every request could be returned as json if the Content-Type is `application/json` and csv if the Content-Type is `text/csv`. That would be the most consistent API.

**Comment by jde** [comment]
Proposed flow after discussing with all parties inolved:

FE Perspective:
1) User clicks on an Export button
2) FE hits an endpoint to render the CSV
3) Askd will return a link to the exported file 
4) FE opens a tab to this new URL

The initial CSV link will be to an API endpoing.
In the future, we will publish the CSV as a file in an object store.
This update will be transparent to the front end (no updates will be needed.)
