### ISSUE TITLE
Admin should be able to sort Forms 

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#49]
- Columns are sortable by the headers (Name - alphabetical/reverse, Submissions - highest/lowest, Creation date - most recent/oldest)
- Skip pagination for now

**Comment by egrdina** [comment]
Step One
![screen shot 2016-08-02 at 11 33 41 am](https://cloud.githubusercontent.com/assets/7856099/17334716/40c38842-58a5-11e6-9638-6711809cec2a.png)

Step Two
![screen shot 2016-08-02 at 11 35 34 am](https://cloud.githubusercontent.com/assets/7856099/17334734/4d7b81c0-58a5-11e6-91a9-654a8f40e859.png)

@IAmSamHankins we should add pagination to our list of things to discuss!

**Comment by pablocubico** [comment]
Why not just adding a "Creation date" column on the table and let users sort by any column?

**Comment by IAmSamHankins** [comment]
it was my understanding that only "sort by date" had been prioritized for this version of Ask (or at this time). the designs here are in error, not reflecting a "created by" column ( @egrdina to provide correction). and this design of sort is designed to be consistent with the "sort" experience in submission manager.

**Comment by pablocubico** [comment]
Ok, so the final version would be: this design + a "created by" column?

**Comment by IAmSamHankins** [comment]
have @egrdina confirm -- not sure if we got rid of a column or not? and i'm not sure what order the columns go in with the addition of date.

**Comment by egrdina** [comment]
The design previously allowed users to sort every column. That was originally deemed too much functionality at the time, so we consolidated the options to a dropdown. @pablocubico are you suggesting we add a Creation date column with the option to sort only that one?

**Comment by losowsky** [comment]
My view is that for now we don't need a Creation date if we have just a single "Newest" or "Oldest" sort. If we're sorting by all columns, that's different (but not necessary for beta 2, would rather we work on other functionality)

**Comment by IAmSamHankins** [comment]
I advocate for having a "creation date" column because it may incongruent to sort a table by a column that does not exist. And unless you know what forms were created by other people before or after yours, you don't necessarily have a frame of reference to know where to find your form.

**Comment by egrdina** [comment]
I think a Creation date column would reinforce to users their sorting the submissions worked. We could add it next to the Submissions total column.

**Comment by pablocubico** [comment]
We already have Creation Date on the database so it's no cost for us to add it:

<img width="1219" alt="captura de pantalla 2016-08-10 a las 13 05 51" src="https://cloud.githubusercontent.com/assets/340766/17561181/417525f0-5efb-11e6-8000-1ed2961419f1.png">

I can keep the design as it is on this issue for consistency with the submission list.

Although, I think that the most commonly found pattern is clicking on the header to sort.

**Comment by egrdina** [comment]
The original design sorted the column by clicking an icon next to the column header. We changed this page so that it's consistent with the Submission Manager sorting. 

Can we hold off on implementing this design until our UI library meeting at 4 today?

**Comment by IAmSamHankins** [comment]
We can definitely circle back on this UI element at some point, esp if we determine other sorts may be useful.

**Comment by egrdina** [comment]
@IAmSamHankins and I are not sending responses at the exact same time intentionally FYI :joy:

**Comment by pablocubico** [comment]
@egrdina let's go with the creation date column added, which again, is no cost, and just add the sorting functionality as it is in this design for this specific case so I can move forward with this. We'll talk about tables and sorting in general on the UI lib meeting. 

Does that make sense?
