### ISSUE TITLE
Admin can easily see what question type each field is in their form

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#50]
- Icons by each field
- Designs below

**Comment by egrdina** [comment]
Icons match each of the icons associated with question types in the left panel.

Short answer
![screen shot 2016-08-02 at 12 00 15 pm](https://cloud.githubusercontent.com/assets/7856099/17335660/b6081ee4-58a8-11e6-8909-048583a04850.png)

Long answer
![screen shot 2016-08-02 at 11 57 52 am](https://cloud.githubusercontent.com/assets/7856099/17335680/c8a9785e-58a8-11e6-9fa4-5a2986d70505.png)

Numbers
![screen shot 2016-08-02 at 11 57 58 am](https://cloud.githubusercontent.com/assets/7856099/17335687/d0561fc6-58a8-11e6-9d1f-923b3cb1c80d.png)

Multiple choice
![screen shot 2016-08-02 at 11 58 02 am](https://cloud.githubusercontent.com/assets/7856099/17335694/d7446b08-58a8-11e6-9730-0ea07dea6c7b.png)

Email 
![screen shot 2016-08-02 at 12 01 48 pm](https://cloud.githubusercontent.com/assets/7856099/17335721/f450cdd6-58a8-11e6-91ff-0b2815e5b426.png)

Date
![screen shot 2016-08-02 at 12 01 54 pm](https://cloud.githubusercontent.com/assets/7856099/17335720/f4498d0a-58a8-11e6-8b21-d2640bf5d34c.png)

Phone number
![screen shot 2016-08-02 at 12 01 59 pm](https://cloud.githubusercontent.com/assets/7856099/17335719/f4479d2e-58a8-11e6-8cef-e4d61f7fb5c1.png)

**Comment by egrdina** [comment]
![screen shot 2016-08-04 at 2 33 00 pm](https://cloud.githubusercontent.com/assets/7856099/17413725/62e0caf0-5a50-11e6-9376-baf959bbae79.png)
![screen shot 2016-08-04 at 2 33 24 pm](https://cloud.githubusercontent.com/assets/7856099/17413734/6fa6f480-5a50-11e6-977e-f64af505af77.png)
![screen shot 2016-08-04 at 2 33 50 pm](https://cloud.githubusercontent.com/assets/7856099/17413753/841cbeae-5a50-11e6-9dd3-d55d1281a98f.png)
![screen shot 2016-08-04 at 2 33 58 pm](https://cloud.githubusercontent.com/assets/7856099/17413754/841f0812-5a50-11e6-862d-b9dbe358e678.png)
![screen shot 2016-08-04 at 2 34 34 pm](https://cloud.githubusercontent.com/assets/7856099/17413800/b325a080-5a50-11e6-854e-5e54ad4296f2.png)
![screen shot 2016-08-04 at 2 34 41 pm](https://cloud.githubusercontent.com/assets/7856099/17413798/b323e7cc-5a50-11e6-8627-0b9934865b89.png)
![screen shot 2016-08-04 at 2 34 45 pm](https://cloud.githubusercontent.com/assets/7856099/17413797/b3234fc4-5a50-11e6-8dcb-8a7c075ff5f5.png)
![screen shot 2016-08-04 at 2 34 51 pm](https://cloud.githubusercontent.com/assets/7856099/17413796/b3233598-5a50-11e6-9cff-f832e384bbf0.png)
![screen shot 2016-08-04 at 2 34 56 pm](https://cloud.githubusercontent.com/assets/7856099/17413799/b325693a-5a50-11e6-8847-9e33b5489bea.png)
![screen shot 2016-08-04 at 2 35 01 pm](https://cloud.githubusercontent.com/assets/7856099/17413801/b3298150-5a50-11e6-897f-04cea66f783b.png)
