### ISSUE TITLE
Move Ask data from "ec2" to "demo.coralproject.net"

### ISSUE THREAD

**Issue by jde** [coralproject/ask#54]
Ask data is contained in three collections:

```
forms
form_submissions
form_galleries
```

Move these collections from our "ec2" host to "Demo"

In the process, create ask-import.sh and ask-export.sh and save them in this repo under /scripts/

**Comment by edefikh** [comment]
The collections have been exported from ec2 instance on 10.0.1.162 to Demo instance 10.0.1.28 

scripts have been saved in ask repo as requested
