### ISSUE TITLE
Add and style Ask Box on our website

### ISSUE THREAD

**Issue by losowsky** [coralproject/ask#66]
![screen shot 2016-08-18 at 12 57 54 pm](https://cloud.githubusercontent.com/assets/10014755/17791320/8fb7184a-6568-11e6-8cf4-469a69111ae9.png)

There's the visual. We'll create a new install of Ask on our AWS that's only for us. (@jtnelson can you do that?)

We also need to make sure that this design works responsively.

**Comment by kgardnr** [comment]
<img width="847" alt="screen_shot_2016-08-19_at_4 06 56_pm" src="https://cloud.githubusercontent.com/assets/1077300/17864008/c38c61ba-6861-11e6-8853-ffdea5582cdb.png">

![report_bug_give_feedback](https://cloud.githubusercontent.com/assets/1077300/17864014/c766e5f8-6861-11e6-8dd2-ffaeda3c3932.png)

**Comment by kgardnr** [comment]
On contributions and contact pages - use same form embed for both. We're also going to use this env for our internal forms: http://ec2-54-175-45-178.compute-1.amazonaws.com/forms

**Comment by kgardnr** [comment]
Embedding the form is done and it's styled pretty closely to above. Take a look!

![ask_form_on_website](https://cloud.githubusercontent.com/assets/1077300/17993658/4745a9a0-6b17-11e6-9642-93deb4e2b5e4.gif)

**Comment by kgardnr** [comment]
Remaining issues:
- [ ] can't embed a non-https form in a https site (Jeff is looking into this)
- [ ] form throws error on submit (screenshot below)

<img width="1259" alt="form_submit_error" src="https://cloud.githubusercontent.com/assets/1077300/17993691/9ad983ca-6b17-11e6-857e-577d934a46ed.png">

**Comment by kgardnr** [comment]
One more issue, I can't get rid of the weird blue outline when you select the text of the form:

<img width="701" alt="weird_blue" src="https://cloud.githubusercontent.com/assets/1077300/17993818/f187ce56-6b18-11e6-8f1e-6c2523838fff.png">

**Comment by losowsky** [comment]
That's related to the accessibility settings - it's always been an issue, let's not fix it for the website, but file it as a bug for next week.

**Comment by kgardnr** [comment]
WOO! Working beautifully!

FORM ADMIN: https://coralinternal.coralproject.net/forms/57c5e461491c7e0007359e6b
