### ISSUE TITLE
Add askd to our staging environment

### ISSUE THREAD

**Issue by jde** [coralproject/ask#69]
The ask service functionality from Pillar is being ported into shelf as a program called askd.

Askd will be built from:

https://github.com/coralproject/shelf/tree/master/cmd/askd (not yet in master, the current code can be found at this branch: https://github.com/coralproject/shelf/tree/ask-refactor/cmd/askd)

Provision a staging server to run the ask service. (t2.small should suffice)

Add a jenkins job to watch for commits to master, build and push to the new server in the same fashion as xenia.

Add configuration to the nginx proxy to make the new server available following the patterns of the current xenia and pillar proxy statement.

**Comment by edefikh** [comment]
The new environment has been setup and tested by Wyatt @ https://askd.coralproject.net 

The setup is automatically deployed via Jenkins and integration with master branch

**Comment by edefikh** [comment]
the new environment works as expected, awaiting further instructions in connecting it to the rest of the stack
