### ISSUE TITLE
Ask demo users should see a welcome screen

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#74]
![screen_shot_2016-08-19_at_3 36 21_pm](https://cloud.githubusercontent.com/assets/1077300/17865331/ba6be8a2-6867-11e6-8872-38e93da4b7a0.png)

======
TEXT:

[The Coral Project logo]

Welcome to Ask, a product of The Coral Project.

You can create and share forms, manage submissions, and create galleries. Learn more about Ask here

This site will reset every 15 minutes. If you have any feedback or find any bugs, please tell us by clicking the link the bottom left.

Thank you!

**Comment by egrdina** [comment]
![contact_desktop_alt](https://cloud.githubusercontent.com/assets/7856099/17865475/be405888-6870-11e6-8bf6-970c56d0036e.jpg)

**Comment by kgardnr** [comment]
Changes to sidebar:
- Remove Create Form and View Form options
- Instead, one menu item that says "Ask"
