### ISSUE TITLE
Coral users can see shortcut menu for Ask

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#75]
- Clicking "?" should show keyboard shortcuts

![screen_shot_2016-08-09_at_11 29 07_am](https://cloud.githubusercontent.com/assets/1077300/17866179/27052976-686b-11e6-9ce4-e71c82dec3a8.png)

**Comment by losowsky** [comment]
We should display the keyboard shortcuts. There's no way to see them right now.
