### ISSUE TITLE
[BUG] With iFrame and Without iFrame tabs show opposite embed codes

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#82]
When you pull up the modal at first, it shows correctly; once you tab, they are incorrect.

![embed_tabs](https://cloud.githubusercontent.com/assets/1077300/18181975/79bc0046-7053-11e6-9250-30f475ea8edd.gif)

**Comment by okbel** [comment]
https://github.com/coralproject/cay/pull/658

**Comment by riley** [comment]
fixed with https://github.com/coralproject/cay/pull/658
