### ISSUE TITLE
Error messaging triggers too early on reader-facing form

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#84]
Errors and alerts should not trigger until a reader is done filling out the question [eg date, numbers]

Date validation error message appears too early -- before someone has even tried to enter a year

<img width="779" alt="date_error" src="https://cloud.githubusercontent.com/assets/1077300/18182173/6359c170-7054-11e6-9b78-49ef9dd06709.png">

**Comment by okbel** [comment]
https://github.com/coralproject/elkhorn/pull/100

**Comment by riley** [comment]
@okbel if I enter a date in only the first box, the form still lets me submit without errors. Is this expected?

https://s3.amazonaws.com/nyt-stage/57d99cf90cefe52294d0ff63.html
