### ISSUE TITLE
BUG:  Setting the min or max. Chars. On a short answer question erases the question, when I click the min or Max. Chars checkbox, everything deletes.

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#89]

**Comment by okbel** [comment]
@kgardnr I'm not able to reproduce this.

Could you (or who reported it) provide me some steps to try to reproduce this? 

![out](https://cloud.githubusercontent.com/assets/1401559/18184740/dab353d2-7070-11e6-989b-463f3c1eb1db.gif)

Thanks!
