### ISSUE TITLE
BUG: When the min value is set, the error message says you need a number above that (though it lies). Either change the message to “Please type n or above” or “needs to be a number above n-1”

### ISSUE THREAD

**Issue by kgardnr** [coralproject/ask#93]
<img width="302" alt="min_value" src="https://cloud.githubusercontent.com/assets/1077300/18182930/99491a76-7057-11e6-97e6-24580982ab04.png">

**Comment by okbel** [comment]
https://github.com/coralproject/elkhorn/pull/89
